### ISSUE TITLE
load model

### ISSUE THREAD

**Issue by FCgogogo** [aliasgharkhani/SLiMe#3]
Traceback (most recent call last):
  File "D:/DL/Segment/SLiMe/src/main.py", line 48, in <module>
    main()
  File "D:/DL/Segment/SLiMe/src/main.py", line 26, in main
    model = Slime(config=config)
  File "D:\DL\Segment\SLiMe\src\slime.py", line 31, in __init__
    self.stable_diffusion = StableDiffusion(
  File "D:\DL\Segment\SLiMe\src\stable_difusion.py", line 41, in __init__
    self.vae = AutoencoderKL.from_pretrained(model_key, subfolder="vae")
  File "D:\DL\Segment\SLiMe\diffusers\models\modeling_utils.py", line 491, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "D:\DL\Segment\SLiMe\diffusers\configuration_utils.py", line 399, in load_config
    raise EnvironmentError(
OSError: Can't load config for 'stabilityai/stable-diffusion-2-1-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-2-1-base' is the correct path to a directory containing a config.json file

Process finished with exit code 1

I upgrade the latest transformer,still have this error!

**Comment by aliasgharkhani** [comment]
It is a problem related to transformers. Try with other versions and make sure that you pass all the parameters correctly. This problem is not related to our code.
